<?php

namespace common\models;

use Yii;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%brand}}".
 *
 * @property int $id
 * @property string $name Name Brand
 * @property string $code
 * @property string $logo
 *
 * @property Product[] $products
 */
class Brand extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%brand}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 45],
            [['code'], 'string', 'max' => 60],
            [['logo'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name Brand',
            'code' => 'Code',
            'logo' => 'Logo',
        ];
    }

    public function beforeSave($insert)
    {
        $this->code = API_WD::createCode($this->name);
        $file = UploadedFile::getInstances($this, 'logo');
        if(!is_null($file)){
            $time = time();
            $type = API_WD::get_extension($file->type);
            $ten_file = API_WD::createCode($this->name);
            $ten_file = "{$time}_logo-{$ten_file}.{$type}";
            $this->logo = $ten_file;
            if(!$insert){
                $thuonghieu = self::findOne($this->id);
                Yii::$app->session->set('old_name_logo', $thuonghieu->logo);
            }
        }
        else{
            if($insert)
                $this->logo = 'no-image.jpg';
            else{
                $thuonghieu = self::findOne($this->id);
                $this->logo = $thuonghieu->logo;
            }
        }
//        VarDumper::dump($file, 10, true);
//        exit;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $file = UploadedFile::getInstances($this, 'logo');
        if(!is_null($file)){
            $ten_file = $this->logo;
            $path = dirname(dirname(__DIR__)).'/images/'.$ten_file;
            //$file->saveAs($path); //?

            if(!$insert){
                $ten_file_cu = Yii::$app->session->get('old_name_logo');
                if($ten_file_cu != 'no-image.jpg'){
                    $path = dirname(dirname(__DIR__)).'/images/'.$ten_file_cu;
                    if(is_file($ten_file_cu))
                        unlink($path);
                }
            }
        }
        else{
            $this->logo = 'no-image.jpg';
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        if($this->logo != 'no-image.jpg'){
            $path = dirname(dirname(__DIR__)).'/images/'.$this->logo;
            if(is_file($path))
                unlink($path);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['brand_id' => 'id']);
    }
}
