<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%slider_images}}".
 *
 * @property int $id
 * @property string $file
 * @property int $slider_id
 *
 * @property Slider $slider
 */
class SliderImages extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%slider_images}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['slider_id'], 'safe'],
            [['file'], 'string', 'max' => 100],
            [['slider_id'], 'exist', 'skipOnError' => true, 'targetClass' => Slider::className(), 'targetAttribute' => ['slider_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file' => 'File',
            'slider_id' => 'Slider ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSlider()
    {
        return $this->hasOne(Slider::className(), ['id' => 'slider_id']);
    }

    //beforeDelete => delete() => afterDelete
    //            [del img in DB]=>[del img in hardware]

    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)).'/images/'.$this->file;
        if(is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
